# Generated by Django 3.0.7 on 2020-06-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='known',
            field=models.BooleanField(default=False),
        ),
    ]
