# Generated by Django 3.0.7 on 2020-06-15 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_auto_20200615_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='dateknown',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learn',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='learn',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
