# Generated by Django 3.0.7 on 2020-06-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20200615_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='flashcards.Language'),
        ),
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flashcards.Level'),
        ),
    ]
