# Generated by Django 3.0.7 on 2020-06-17 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0007_auto_20200616_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='flashcards.Language')),
                ('level', models.ForeignKey(default='HSK1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flashcards.Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
